name: intogen_deconstructsig
channels:
- bbglab
- bioconda
- r
- conda-forge
- defaults
dependencies:
- ca-certificates=2017.1.23=1
- bioconductor-biobase=2.38.0=r3.4.1_0
- bioconductor-biocgenerics=0.24.0=r3.4.1_0
- bioconductor-biocparallel=1.12.0=r3.4.1_0
- bioconductor-biostrings=2.46.0=r3.4.1_0
- bioconductor-bsgenome=1.46.0=r3.4.1_0
- bioconductor-bsgenome.hsapiens.ucsc.hg19=1.4.0=r3.4.1_0
- bioconductor-delayedarray=0.4.1=r3.4.1_0
- bioconductor-genomeinfodb=1.14.0=r3.4.1_0
- bioconductor-genomeinfodbdata=0.99.0=r3.4.1_0
- bioconductor-genomicalignments=1.14.1=r3.4.1_0
- bioconductor-genomicranges=1.30.3=r3.4.1_0
- bioconductor-iranges=2.12.0=r3.4.1_0
- bioconductor-rsamtools=1.30.0=r3.4.1_0
- bioconductor-rtracklayer=1.38.0=r3.4.1_0
- bioconductor-s4vectors=0.16.0=r3.4.1_0
- bioconductor-summarizedexperiment=1.8.0=r3.4.1_0
- bioconductor-xvector=0.18.0=r3.4.1_0
- bioconductor-zlibbioc=1.24.0=r3.4.1_0
- r-deconstructsigs=1.8.0=r3.4.1_0
- r-base=3.4.1=0
- r-futile.logger=1.4.3=r3.4.1_0
- r-futile.options=1.0.0=r3.4.1_0
- r-lambda.r=1.2=r3.4.1_0
- r-matrixstats=0.52.2=r3.4.1_0
- r-snow=0.4_2=r3.4.1_0
- readline=6.2=0
- bzip2=1.0.6=h9a117a8_4
- cairo=1.14.8=0
- curl=7.52.1=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- gsl=2.4=h1bed415_3
- harfbuzz=0.9.39=2
- icu=58.2=h9c2bf20_1
- jbig=2.1=hdba287a_0
- jpeg=9b=h024ee3a_2
- libffi=3.2.1=hd88cf55_4
- libgcc=7.2.0=h69d50b8_2
- libgcc-ng=7.2.0=hdf63c60_3
- libiconv=1.14=0
- libpng=1.6.30=1
- libstdcxx-ng=7.2.0=hdf63c60_3
- libtiff=4.0.6=3
- libxml2=2.9.4=0
- ncurses=5.9=10
- openssl=1.0.2o=h20670df_0
- pango=1.40.3=1
- pcre=8.39=1
- pixman=0.34.0=hceecf20_3
- tk=8.5.18=0
- xz=5.2.3=h55aa19d_2
- zlib=1.2.8=3
- r-bh=1.62.0_1=r3.4.1_0
- r-bitops=1.0_6=r3.4.1_2
- r-catools=1.17.1=r3.4.1_2
- r-gdata=2.18.0=r3.4.1_0
- r-gplots=3.0.1=r3.4.1_0
- r-gtools=3.5.0=r3.4.1_0
- r-kernsmooth=2.23_15=r3.4.1_0
- r-lattice=0.20_35=r3.4.1_0
- r-magrittr=1.5=r3.4.1_2
- r-matrix=1.2_10=r3.4.1_0
- r-plyr=1.8.4=r3.4.1_0
- r-rcpp=0.12.11=r3.4.1_0
- r-rcurl=1.95_4.8=r3.4.1_0
- r-reshape2=1.4.2=r3.4.1_0
- r-stringi=1.1.5=r3.4.1_0
- r-stringr=1.2.0=r3.4.1_0
- r-xml=3.98_1.7=r3.4.1_0

